secrets:
  SecretKey:
    file: docker/secrets/secret_key.txt
  DBPassword:
    file: docker/secrets/db_password.txt
  GOOGLE_API_KEY:
    file: docker/secrets/google_api_key.txt

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:16-3.5
    networks:
      - default
    environment:
      - POSTGRES_USER=invasives
      - POSTGRES_PASSWORD=invasives
      - POSTGRES_DB=invasives
    volumes:
      - ${VOLUME_PATH}/postgres/16/main:/var/lib/postgresql/data
      - ${VOLUME_PATH}/dumps:/archive
    ports:
      - 5439:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invasives"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.1-alpine
    networks:
      - default
    volumes:
      - ${VOLUME_PATH}/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq-dev'
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bootstrap:
    build:
      context: .
      dockerfile: docker/bootstrap/Dockerfile
      args:
        - APP_USER_ID=${USER_ID}
        - APP_GROUP_ID=${GROUP_ID}
    environment:
      - EMCEE_CMD_ENV=docker
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ${VOLUME_PATH}/static:/static
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - SecretKey
      - DBPassword
    user: '${USER_ID}'

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - APP_USER_ID=${USER_ID}
        - APP_GROUP_ID=${GROUP_ID}
        - APP_ENVIRONMENT=development
    environment:
      - EMCEE_CMD_ENV=docker
      - APP_ENVIRONMENT=development
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ${VOLUME_PATH}/static:/static
      - ./:/app
      # - ./media:/media
    depends_on:
      postgres:
        condition: service_healthy
      celery:
        condition: service_started
      bootstrap:
          condition: service_completed_successfully
    secrets:
      - SecretKey
      - DBPassword
      - GOOGLE_API_KEY
    user: '${USER_ID}'

  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
      args:
        - APP_USER_ID=${USER_ID}
        - APP_GROUP_ID=${GROUP_ID}
    environment:
      - EMCEE_CMD_ENV=docker
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/media:/media
      - ./:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    secrets:
      - SecretKey
      - DBPassword
    user: '${USER_ID}'
