# Generated by Django 5.2.8 on 2025-11-12 20:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('prefix', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Is Manager (can login and manage reports)')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='Is Admin (can do anything)')),
                ('affiliations', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('has_completed_ofpd', models.BooleanField(blank=True, default=False, verbose_name='\n        Check this box if you have completed the Oregon\n        Forest Pest Detector training, offered by Oregon State\n        Extension.')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
