# Generated by Django 5.2.8 on 2025-12-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_make_first_and_last_name_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_completed_ofpd',
            field=models.BooleanField(blank=True, default=False, verbose_name='\n        Check this box if you have completed the Oregon\n        Forest Pest Detector training, offered by Oregon State\n        Extension.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is Manager (can login and manage reports)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Admin (can do anything)'),
        ),
    ]
