# Generated by Django 6.0.2 on 2026-05-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_has_completed_ofpd_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_completed_ofpd',
        ),
    ]
