# Generated by Django 5.2.8 on 2025-11-12 20:30

import django.db.models.deletion
import oregoninvasiveshotline.visibility
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateField(auto_now=True)),
                ('visibility', models.IntegerField(choices=[(0, 'Private - only managers and invited experts can see'), (1, 'Protected - only managers, invited experts and the report submitter can see'), (2, 'Public - everyone can see (when this report is made public)')], default=1, help_text='Controls who can see this comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_on', 'pk'],
            },
            bases=(oregoninvasiveshotline.visibility.Visibility, models.Model),
        ),
    ]
