# Generated by Django 5.2.8 on 2025-12-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_change_default_visibility'),
        ('reports', '0007_change_default_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report'),
        ),
    ]
