# Generated by Django 5.2.8 on 2025-11-12 20:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counties', '0001_initial'),
        ('species', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Please provide a description of your find')),
                ('location', models.TextField(help_text='\n            For example name the road, trail or specific landmarks\n            near the site whether the species was found. Describe the geographic\n            location, such as in a ditch, on a hillside or in a streambed. If you\n            happen to have taken GPS coordinates, enter them here.\n        ', verbose_name='Please provide a description of the area where species was found')),
                ('has_specimen', models.BooleanField(default=False, verbose_name='Do you have a physical specimen?')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edrr_status', models.IntegerField(blank=True, choices=[(None, ''), (0, 'No Response/Action Required'), (1, 'Local expert notified'), (2, 'Population assessed'), (3, 'Population treated'), (4, 'Ongoing monitoring'), (5, 'Controlled at site')], default=None, null=True, verbose_name='EDRR Status')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='This report can be viewed by the public')),
                ('actual_species', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='species.species')),
                ('claimed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reports', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='counties.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('reported_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.category')),
                ('reported_species', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='species.species')),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invite_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'invite',
            },
        ),
    ]
