# Generated by Django 6.0.2 on 2026-06-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_change_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='identification_process',
            field=models.TextField(null=True, blank=True),
        ),
    ]
