# Generated by Django 6.0.2 on 2026-07-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_identification_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Please provide a description of your find'),
        ),
        migrations.AlterField(
            model_name='report',
            name='identification_process',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.TextField(help_text='\n            For example name the road, trail or specific landmarks\n            near the site whether the species was found. Describe the geographic\n            location, such as in a ditch, on a hillside or in a streambed. If you\n            happen to have taken GPS coordinates, enter them here.\n        ', max_length=3000, verbose_name='Please provide a description of the area where species was found'),
        ),
    ]
