# Generated by Django 5.2.8 on 2025-11-12 20:30

import django.db.models.deletion
import oregoninvasiveshotline.visibility
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('reports', '0001_initial'),
        ('species', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.IntegerField(choices=[(0, 'Private - only managers and invited experts can see'), (1, 'Protected - only managers, invited experts and the report submitter can see'), (2, 'Public - everyone can see (when this report is made public)')], default=1)),
                ('comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
                ('species', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.species')),
            ],
            options={
                'db_table': 'image',
                'ordering': ['pk'],
            },
            bases=(oregoninvasiveshotline.visibility.Visibility, models.Model),
        ),
    ]
