# Generated by Django 5.2.8 on 2025-11-12 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='It is expected that the icon came from http://mapicons.mapsmarker.com/ and that it has a transparent background with a white foreground', null=True, upload_to='icons')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('severity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(help_text='An HTML color of the form "#rrggbb"', max_length=7, validators=[django.core.validators.RegexValidator('#[0-9A-Fa-f]{6}')])),
            ],
            options={
                'db_table': 'severity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_confidential', models.BooleanField(default=False, help_text='A species can be marked as confidential if making a report about it public would cause harm')),
                ('name', models.CharField(max_length=255)),
                ('remedy', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.category')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.severity')),
            ],
            options={
                'db_table': 'species',
                'ordering': ['name'],
            },
        ),
    ]
