# Generated by Django 6.0.2 on 2026-04-01 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_update_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='identification_external_resource_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='identification_image',
            field=models.ImageField(blank=True, null=True, upload_to='identification_images/'),
        ),
        migrations.AddField(
            model_name='species',
            name='identification_image_alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='species.category'),
        ),
    ]
