# Generated by Django 6.0.2 on 2026-05-01 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_update_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='species.category'),
        ),
    ]
