# Generated by Django 6.0.2 on 2026-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_species_identification_external_resource_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='identification_external_resource_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='identification_image_alt',
            field=models.CharField(blank=True, null=True),
        ),
    ]
